---
- name: Add grafana yum repository
  ansible.builtin.copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
  become: true

- name: Install grafana
  ansible.builtin.yum:
    name: grafana
    state: present
  become: true

- name: Start Grafana
  ansible.builtin.systemd:
    name: grafana-server
    daemon_reload: true
    state: started
    enabled: true
  become: true
